---
title: "gtsummary in quarto"
format: html
execute:
  echo: false
---

```{r}
#| output: false
library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd",
							 "id", "nsibs", "samp", "race_eth", "sex", "region",
							 "income", "res_1980", "res_2002", "age_bir")

nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |> 
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes"))) 
```

```{r}
nrow(nlsy)
```
# Customization of `tbl_summary()`

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))
```

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir),
  label = list(
    race_eth_cat ~ "Race/ethnicity",
    region_cat ~ "Region",
    eyesight_cat ~ "Eyesight",
    glasses ~ "Wears glasses",
    age_bir ~ "Age at first birth"
  ),
  missing_text = "Missing")
```

```{r}
#| label: tbl-one
#| tbl-cap: "Variables measured"
tbl_summary(
	nlsy,
	by = sex_cat,
	include =c(sex_cat, race_eth_cat, region_cat, eyesight_cat, glasses, age_bir),
	label = list(
		race_eth_cat ~ "Race/ethnicity or   something",
		region_cat ~ "Regional area dude", 
		eyesight_cat ~ "Goodness of eyeness",
		glasses ~ "Wears goggles",
		age_bir ~ "Age"
		),
	missing_text = "Missing")
```
@tbl-one shows various categories. There were `r nrow(nlsy)` participants.

```{r}
stats <- list(n=nrow(nlsy),
							mean_sleep = mean(nlsy$sleep_wknd,na.rm = TRUE))
```

The average sleep on the weekend was `r median(nlsy$sleep_wknd,na.rm = TRUE)`


```{r}
#| label: tbl_descr
#| tbl-cap: "Descriptive Stats"
table_1<- tbl_summary(nlsy,
by = sex_cat,
										 include =c(sex_cat, race_eth_cat, region_cat, eyesight_cat, glasses, age_bir, sleep_wknd)) |>
add_overall(last = TRUE)
table_1
inline_text(table_1, variable = "sleep_wknd", column = "stat_0")
```
```{r}
sleep_f <-inline_text(table_1, variable = "sleep_wknd", column = "stat_2")
sleep_m <-inline_text(table_1, variable = "sleep_wknd", column = "stat_1")
```
a lesser proportion of male (`r sleep_m`) than female (`r sleep_f`)

